In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from xgboost.sklearn import XGBClassifier
import xgboost as xgb

In [39]:
data=pd.read_csv("Financial_Risk_Participants_Data/train.csv")

In [40]:
data.head()

City  Location_Score  Internal_Audit_Score  External_Audit_Score  \
0     2           8.032                    14                     8   
1    31          77.730                     8                     3   
2    40          59.203                     3                    12   
3    12          73.080                     4                     5   
4     4          15.666                    13                    15   

   Fin_Score  Loss_score  Past_Results  IsUnderRisk  
0          3           6             0            1  
1          3           8             1            0  
2         11           3             0            1  
3          7           6             0            0  
4          6           7             2            1

In [41]:
data.describe()


City  Location_Score  Internal_Audit_Score  External_Audit_Score  \
count  543.000000      543.000000            543.000000            543.000000   
mean    19.576427       32.259346              8.189687              7.327808   
std     14.722687       24.887291              3.312022              3.450667   
min      0.000000        5.185000              3.000000              3.000000   
25%      6.000000       13.565000              6.000000              5.000000   
50%     14.000000       19.803000              8.000000              7.000000   
75%     37.000000       62.594000             11.000000             10.000000   
max     44.000000       80.809000             15.000000             15.000000   

        Fin_Score  Loss_score  Past_Results  IsUnderRisk  
count  543.000000  543.000000    543.000000   543.000000  
mean     7.046041    5.530387      0.613260     0.626151  
std      3.156978    1.839124      0.764509     0.484270  
min      3.000000    3.000000      0.000000     0.000000  
25%      5.000000    4.000000      0.000000     0.000000  
50%      7.000000    6.000000      1.000000     1.000000  
75%      8.000000    7.000000      1.000000     1.000000  
max     15.000000   13.000000     10.000000     1.000000

In [42]:
data.corr()

City  Location_Score  Internal_Audit_Score  \
City                  1.000000        0.012551             -0.024306   
Location_Score        0.012551        1.000000             -0.358629   
Internal_Audit_Score -0.024306       -0.358629              1.000000   
External_Audit_Score -0.049994       -0.205775              0.453839   
Fin_Score            -0.051779       -0.264536              0.365133   
Loss_score            0.033183       -0.042139              0.007685   
Past_Results          0.004762       -0.074364              0.112093   
IsUnderRisk          -0.087463       -0.423956              0.586097   

                      External_Audit_Score  Fin_Score  Loss_score  \
City                             -0.049994  -0.051779    0.033183   
Location_Score                   -0.205775  -0.264536   -0.042139   
Internal_Audit_Score              0.453839   0.365133    0.007685   
External_Audit_Score              1.000000   0.433374   -0.038786   
Fin_Score                         0.433374   1.000000   -0.078573   
Loss_score                       -0.038786  -0.078573    1.000000   
Past_Results                      0.141163   0.138111    0.081858   
IsUnderRisk                       0.435619   0.362463    0.044888   

                      Past_Results  IsUnderRisk  
City                      0.004762    -0.087463  
Location_Score           -0.074364    -0.423956  
Internal_Audit_Score      0.112093     0.586097  
External_Audit_Score      0.141163     0.435619  
Fin_Score                 0.138111     0.362463  
Loss_score                0.081858     0.044888  
Past_Results              1.000000     0.102120  
IsUnderRisk               0.102120     1.000000

In [43]:
data['Past_Results'].unique()

array([ 0,  1,  2,  3,  4,  6, 10], dtype=int64)

In [44]:
data['Loss_score'].unique()

array([ 6,  8,  3,  7,  4,  5, 11,  9, 10, 13], dtype=int64)

In [45]:
data['City'].unique()


array([ 2, 31, 40, 12,  4,  1,  9, 23, 38,  0, 10,  8, 11, 19,  6, 37,  3,
        5, 41, 16, 22, 29, 28, 18, 35, 13, 32, 14, 30, 43, 39, 21, 24, 25,
       17, 33, 15, 27, 20,  7, 42, 44, 26], dtype=int64)

In [46]:
data['Fin_Score'].unique()

array([ 3, 11,  7,  6, 12,  5,  4, 14,  8, 15, 13, 10,  9], dtype=int64)

In [47]:
data['External_Audit_Score'].unique()

array([ 8,  3, 12,  5, 15, 10,  4,  7, 11,  6, 14, 13,  9], dtype=int64)

In [48]:
data['External_Audit_Score'].unique()

array([ 8,  3, 12,  5, 15, 10,  4,  7, 11,  6, 14, 13,  9], dtype=int64)

In [49]:
feature_data = data


In [50]:
target=data['IsUnderRisk']

In [51]:
feature_data=data

In [52]:
feature_data.head()

City  Location_Score  Internal_Audit_Score  External_Audit_Score  \
0     2           8.032                    14                     8   
1    31          77.730                     8                     3   
2    40          59.203                     3                    12   
3    12          73.080                     4                     5   
4     4          15.666                    13                    15   

   Fin_Score  Loss_score  Past_Results  IsUnderRisk  
0          3           6             0            1  
1          3           8             1            0  
2         11           3             0            1  
3          7           6             0            0  
4          6           7             2            1

In [53]:
feature_data = feature_data.drop(['IsUnderRisk'],axis=1)
feature_data = feature_data.drop(['Loss_score'],axis=1)  # corr coeff is 0.044888
feature_data = feature_data.drop(['Past_Results'],axis=1)
feature_data = feature_data.drop(['Location_Score'],axis=1)
#feature_data = feature_data.drop(['Fin_Score'],axis=1)



In [54]:
feature_data['art']=data['Location_Score']+data['Loss_score']+data['Past_Results']

In [55]:
target.head()  

0    1
1    0
2    1
3    0
4    1
Name: IsUnderRisk, dtype: int64

In [56]:
feature_data.head()

City  Internal_Audit_Score  External_Audit_Score  Fin_Score     art
0     2                    14                     8          3  14.032
1    31                     8                     3          3  86.730
2    40                     3                    12         11  62.203
3    12                     4                     5          7  79.080
4     4                    13                    15          6  24.666

In [57]:
feature_data.head()

City  Internal_Audit_Score  External_Audit_Score  Fin_Score     art
0     2                    14                     8          3  14.032
1    31                     8                     3          3  86.730
2    40                     3                    12         11  62.203
3    12                     4                     5          7  79.080
4     4                    13                    15          6  24.666

In [58]:
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY = train_test_split(feature_data,target,test_size=0.33, random_state=47)

In [59]:

from xgboost import XGBClassifier

In [60]:
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY = train_test_split(feature_data,target,test_size=0.33, random_state=47)
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY = train_test_split(feature_data,target,test_size=0.33, random_state=47)
xgb=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
              max_depth=4, min_child_weight=1, missing=None, n_estimators=26,
              n_jobs=6, nthread=None, objective='binary:logistic',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=None, silent=True, subsample=1)


In [61]:
xgb.fit(trainX,trainY)

predictions=xgb.predict(testX)

from sklearn.metrics import classification_report

print(classification_report(testY,predictions))

              precision    recall  f1-score   support

           0       0.71      0.93      0.81        67
           1       0.95      0.78      0.85       113

    accuracy                           0.83       180
   macro avg       0.83      0.85      0.83       180
weighted avg       0.86      0.83      0.84       180



In [62]:
xgb.feature_importances_

array([0.19166666, 0.275     , 0.15833333, 0.20833333, 0.16666667],
      dtype=float32)

In [63]:
test=pd.read_csv("Financial_Risk_Participants_Data/test.csv")
test['art']=test['Location_Score']+test['Loss_score']+test['Past_Results']
test = test.drop(['Loss_score'],axis=1)
test = test.drop(['Past_Results'],axis=1)
test = test.drop(['Location_Score'],axis=1)


test.head()

City  Internal_Audit_Score  External_Audit_Score  Fin_Score     art
0    41                    13                    12          9  25.272
1    17                     6                    10          7  69.799
2    31                     3                     3          7  76.890
3     3                    15                    10          7  21.492
4     9                     7                     3          8  21.178

In [64]:
Result=xgb.predict_proba(test)

In [65]:
df = pd.DataFrame(data=Result, columns=["0", "1"])

In [66]:
df.head()

0         1
0  0.042448  0.957552
1  0.194546  0.805454
2  0.828934  0.171066
3  0.042448  0.957552
4  0.482620  0.517380

In [67]:
df.to_excel("submission.xlsx", index=False)